# Generated by Django 5.1.3 on 2025-05-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(max_length=2000),
        ),
    ]
