# Generated by Django 5.2 on 2025-05-03 01:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0007_alter_blog_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
