# Generated by Django 5.1.3 on 2025-05-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0008_alter_blog_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
    ]
