# Generated by Django 5.1.3 on 2025-05-05 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0010_blog_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="tag",
            field=models.ForeignKey(
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blogapp.tag",
            ),
        ),
    ]
