# Generated by Django 5.1.3 on 2025-05-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0011_alter_blog_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
    ]
