# Generated by Django 5.2 on 2025-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0012_blog_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
