# Generated by Django 5.1.3 on 2025-06-29 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0013_review_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blogapp.tag",
            ),
        ),
    ]
